### ISSUE TITLE
Why is the image blurry after relighting?

### ISSUE THREAD

**Issue by helloxuejuxi** [andrewhou1/Shadow-Mask-Face-Relighting#2]
Why is the image blurry after relighting?Looking forward to your reply,thanks a lot

**Comment by andrewhou1** [comment]
Our model operates on 256x256 images as input. The images in the sample_outputs/ folder, which are the relit images, are therefore 256x256. They may appear more blurry than the images in the sample_images/ folder since those are the original images from FFHQ before resizing, and are 1024x1024.

**Comment by helloxuejuxi** [comment]
> Our model operates on 256x256 images as input. The images in the sample_outputs/ folder, which are the relit images, are therefore 256x256. They may appear more blurry than the images in the sample_images/ folder since those are the original images from FFHQ before resizing, and are 1024x1024.

thank you very much
