### ISSUE TITLE
Face normal retrieval

### ISSUE THREAD

**Issue by FeiiYin** [andrewhou1/Shadow-Mask-Face-Relighting#9]
Hi, thanks for the amazing work!
I wondered can the work extract the face normals of the target face?
And can you provide a script or some advice?
Thanks in advance!

**Comment by andrewhou1** [comment]
Hi there, thanks for your interest in our work! This relighting method is inherently image-to-image, and we don't decompose into the intrinsic components (normals, albedo, light, pose). The ratio image is regressed directly from the input image given a target light so we don't estimate the normals in between.

**Comment by FeiiYin** [comment]
Thanks!
